version: '3.6'
services:
    nginx:
        restart: always
        build: ./frontend
        volumes:
            - ./statics:/usr/local/openresty/nginx/statics
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
        depends_on:
            - node

    node:
        restart: always
        build: ./backend
        depends_on:
            - db

    db:
        restart: always
        image: postgres:12-alpine
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        env_file:
            - docker.env
